// CHC Corporate API — chc-corporate-api
// Auto-generated by Script 20 — DO NOT hand edit
// Deployed to GCP Cloud Run · Same pattern as chc-virtual-bank

const express = require('express');
const app = express();
app.use(require('cors')({ origin: 'https://portal.coreholdingcorp.com', credentials: true })); app.use((req, res, next) => {   res.setHeader('Cross-Origin-Resource-Policy', 'cross-origin');   res.setHeader('Cross-Origin-Opener-Policy', 'unsafe-none');   next(); });
app.use((req, res, next) => {   res.setHeader('Access-Control-Allow-Origin', 'https://portal.coreholdingcorp.com');   res.setHeader('Access-Control-Allow-Methods', 'GET,POST,PUT,DELETE,OPTIONS');   res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization, x-api-key');   res.setHeader('Access-Control-Allow-Credentials', 'true');   res.setHeader('Cross-Origin-Resource-Policy', 'cross-origin');   if (req.method === 'OPTIONS') return res.sendStatus(200);   next(); });
app.use((req, res, next) => {   res.setHeader('Access-Control-Allow-Origin', 'https://portal.coreholdingcorp.com');   res.setHeader('Access-Control-Allow-Methods', 'GET,POST,PUT,DELETE,OPTIONS');   res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization, x-api-key');   res.setHeader('Access-Control-Allow-Credentials', 'true');   res.setHeader('Cross-Origin-Resource-Policy', 'cross-origin');   if (req.method === 'OPTIONS') return res.sendStatus(200);   next(); });
app.use(express.json());

// ── Auth middleware ───────────────────────────────────────────
const API_KEY = process.env.CHC_CORP_API_KEY || 'chc-corp-dev-key-2026';
function auth(req, res, next) {
  if (req.path === '/health') return next();
  const key = req.headers['x-api-key'];
  if (key !== API_KEY) return res.status(401).json({ error: 'Unauthorized' });
  next();
}
app.use(auth);

// ── Data ─────────────────────────────────────────────────────
const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

const coreIdentityData = {
  id: 'coreidentity',
  name: 'CoreIdentity',
  type: 'SaaS Platform',
  description: 'Agentic AI Governance Platform',
  incorporated: '2024',
  state: 'Wyoming',
  parent: 'Core Holding Corp',
  metrics: {
    mrr: 142000,
    arr: 1704000,
    customers: 8,
    nrr: 118,
    netMargin: 81,
    netProfit: 115500
  },
  monthly: {
    revenue: [78000,82000,88000,92000,98000,105000,112000,118000,122000,128000,135000,142000],
    targets:  [85000,90000,96000,102000,109000,116000,123000,130000,136000,142000,149000,156000],
    costs:    [21000,21500,22000,22500,23000,23500,24000,24500,25000,25500,26000,26500]
  },
  infrastructure: {
    cloud: 'AWS ECS Fargate',
    region: 'us-east-1',
    cicd: 'GitHub Actions',
    deploymentTime: '<60 seconds'
  },
  agents: [
    { id:'ci-01', name:'Governance Policy Engine',  category:'Core',           status:'ACTIVE', executions:14823, governed:true, uptime:99.9 },
    { id:'ci-02', name:'Compliance Monitor Alpha',   category:'Compliance',     status:'ACTIVE', executions:9241,  governed:true, uptime:99.8 },
    { id:'ci-03', name:'Compliance Monitor Beta',    category:'Compliance',     status:'ACTIVE', executions:8876,  governed:true, uptime:99.8 },
    { id:'ci-04', name:'Compliance Monitor Gamma',   category:'Compliance',     status:'ACTIVE', executions:7654,  governed:true, uptime:99.7 },
    { id:'ci-05', name:'Sentinel Health Check',      category:'Security',       status:'ACTIVE', executions:22410, governed:true, uptime:100  },
    { id:'ci-06', name:'Nexus Circuit Breaker',      category:'Infrastructure', status:'ACTIVE', executions:3201,  governed:true, uptime:100  },
    { id:'ci-07', name:'SmartNation Telemetry',      category:'Analytics',      status:'ACTIVE', executions:18904, governed:true, uptime:99.9 },
    { id:'ci-08', name:'API Gateway Agent',          category:'Infrastructure', status:'ACTIVE', executions:31205, governed:true, uptime:100  },
    { id:'ci-09', name:'Rate Limiter Agent',         category:'Infrastructure', status:'ACTIVE', executions:28941, governed:true, uptime:100  },
    { id:'ci-10', name:'Audit Trail Agent',          category:'Compliance',     status:'ACTIVE', executions:12033, governed:true, uptime:99.9 },
    { id:'ci-11', name:'Alert & Notification',       category:'Operations',     status:'ACTIVE', executions:4521,  governed:true, uptime:99.6 },
    { id:'ci-12', name:'Dashboard Analytics',        category:'Analytics',      status:'ACTIVE', executions:8103,  governed:true, uptime:99.7 },
    { id:'ci-13', name:'Integration Health',         category:'Infrastructure', status:'ACTIVE', executions:6782,  governed:true, uptime:99.8 },
    { id:'ci-14', name:'Security Posture Agent',     category:'Security',       status:'ACTIVE', executions:5432,  governed:true, uptime:99.9 },
    { id:'ci-15', name:'SLA Enforcement Agent',      category:'Operations',     status:'ACTIVE', executions:9871,  governed:true, uptime:99.8 }
  ]
};

const ciagData = {
  id: 'ciag',
  name: 'CIAG',
  type: 'Advisory Group',
  description: 'CoreIdentity Advisory Group',
  incorporated: '2024',
  state: 'Wyoming',
  parent: 'Core Holding Corp',
  metrics: {
    mrr: 153000,
    retainerMrr: 88000,
    projectRevenue: 65000,
    netMargin: 68,
    netProfit: 104000,
    activeRetainers: 4,
    activeProjects: 3
  },
  monthly: {
    retainerRevenue: [48000,52000,54000,60000,66000,70000,72000,72000,78000,82000,85000,88000],
    projectRevenue:  [15000,22000,35000,28000,42000,38000,55000,48000,62000,58000,72000,65000],
    targets:         [70000,78000,90000,92000,115000,112000,130000,125000,145000,145000,162000,158000],
    costs:           [38000,39000,40000,41000,42000,43000,44000,45000,46000,47000,48000,49000]
  },
  retainers: [
    { id:'r-01', client:'Meridian Wealth Partners LLC',     monthly:22000, status:'ACTIVE', since:'Mar 2025', frameworks:['GLBA','CCPA'],     autoRenew:true },
    { id:'r-02', client:'Harbor Point Investment Group',    monthly:18000, status:'ACTIVE', since:'May 2025', frameworks:['GLBA','SOX'],      autoRenew:true },
    { id:'r-03', client:'Pacific Crest Financial Services', monthly:28000, status:'ACTIVE', since:'Jun 2025', frameworks:['CCPA','PCI-DSS'],  autoRenew:true },
    { id:'r-04', client:'Summit Valley Bank',               monthly:20000, status:'ACTIVE', since:'Sep 2025', frameworks:['FFIEC','GLBA'],    autoRenew:false }
  ],
  projects: [
    { id:'p-01', name:'AI Governance Readiness Assessment', client:'Westlake Regional CU',     value:85000,  completion:68, status:'IN_PROGRESS', eta:'Apr 2026' },
    { id:'p-02', name:'CCPA + GLBA Compliance Mapping',     client:'Meridian Wealth Partners', value:45000,  completion:82, status:'IN_PROGRESS', eta:'Mar 2026' },
    { id:'p-03', name:'Texas RAIGA Implementation Plan',    client:'Regional Bank Consortium', value:120000, completion:35, status:'ACTIVE',      eta:'Jun 2026' }
  ],
  agents: [
    { id:'cg-01', name:'Client Assessment Agent',     category:'Onboarding', status:'ACTIVE', executions:3204, governed:true, uptime:99.7 },
    { id:'cg-02', name:'Regulatory Mapping Agent',    category:'Compliance', status:'ACTIVE', executions:2891, governed:true, uptime:99.8 },
    { id:'cg-03', name:'Compliance Gap Analyzer',     category:'Compliance', status:'ACTIVE', executions:4102, governed:true, uptime:99.9 },
    { id:'cg-04', name:'Executive Report Generator',  category:'Reporting',  status:'ACTIVE', executions:1203, governed:true, uptime:99.5 },
    { id:'cg-05', name:'Risk Scoring Agent',          category:'Risk',       status:'ACTIVE', executions:5671, governed:true, uptime:99.8 },
    { id:'cg-06', name:'Remediation Planner',         category:'Operations', status:'ACTIVE', executions:2341, governed:true, uptime:99.6 },
    { id:'cg-07', name:'Client Portal Agent',         category:'Delivery',   status:'ACTIVE', executions:8934, governed:true, uptime:99.9 },
    { id:'cg-08', name:'Engagement Tracker',          category:'Operations', status:'ACTIVE', executions:1567, governed:true, uptime:99.7 }
  ]
};

function buildConsolidated() {
  const ciagRev = ciagData.monthly.retainerRevenue.map((r,i) => r + ciagData.monthly.projectRevenue[i]);
  const revenue = coreIdentityData.monthly.revenue.map((r,i) => r + ciagRev[i]);
  const targets = coreIdentityData.monthly.targets.map((t,i) => t + ciagData.monthly.targets[i]);
  const costs   = coreIdentityData.monthly.costs.map((c,i)   => c + ciagData.monthly.costs[i]);
  const profit  = revenue.map((r,i) => r - costs[i]);
  const margin  = revenue.map((r,i) => Math.round((r - costs[i]) / r * 100));
  return { MONTHS, revenue, targets, costs, profit, margin };
}

// ── Governance sync store (in-memory) ────────────────────────
const governanceSyncs = [];

// ── Routes ───────────────────────────────────────────────────
app.get('/health', (req, res) => {
  res.json({
    status: 'healthy',
    service: 'CHC Corporate API',
    version: '1.0.0',
    entities: ['CoreIdentity','CIAG'],
    timestamp: new Date().toISOString()
  });
});

app.get('/api/company', (req, res) => {
  const cons = buildConsolidated();
  const cur  = cons.revenue.length - 1;
  res.json({
    name: 'Core Holding Corp',
    ticker: 'CHC',
    type: 'Wyoming Private Holding Company',
    structure: 'own nothing, control everything',
    subsidiaries: ['CoreIdentity','CIAG'],
    consolidated: {
      mrr:       cons.revenue[cur],
      arr:       cons.revenue[cur] * 12,
      netProfit: cons.profit[cur],
      netMargin: cons.margin[cur],
      totalAgents: coreIdentityData.agents.length + ciagData.agents.length,
      governedAgents: coreIdentityData.agents.length + ciagData.agents.length
    },
    generatedAt: new Date().toISOString()
  });
});

app.get('/api/coreidentity', (req, res) => {
  res.json({ success:true, data: coreIdentityData, generatedAt: new Date().toISOString() });
});

app.get('/api/ciag', (req, res) => {
  res.json({ success:true, data: ciagData, generatedAt: new Date().toISOString() });
});

app.get('/api/financials', (req, res) => {
  res.json({ success:true, data: buildConsolidated(), generatedAt: new Date().toISOString() });
});

app.get('/api/agents', (req, res) => {
  const all = [
    ...coreIdentityData.agents.map(a => ({...a, subsidiary:'CoreIdentity'})),
    ...ciagData.agents.map(a => ({...a, subsidiary:'CIAG'}))
  ];
  res.json({
    success: true,
    total: all.length,
    governed: all.filter(a => a.governed).length,
    bySubsidiary: { CoreIdentity: coreIdentityData.agents.length, CIAG: ciagData.agents.length },
    data: all,
    generatedAt: new Date().toISOString()
  });
});

app.post('/api/governance/sync', (req, res) => {
  const { source, agents, metrics, timestamp } = req.body;
  const sync = { source, agents, metrics, timestamp: timestamp || new Date().toISOString(), receivedAt: new Date().toISOString() };
  governanceSyncs.push(sync);
  res.json({
    success: true,
    message: 'Governance telemetry received',
    syncId: 'sync-' + Date.now(),
    syncsTotal: governanceSyncs.length
  });
});

app.get('/api/governance/syncs', (req, res) => {
  res.json({ success:true, count: governanceSyncs.length, data: governanceSyncs.slice(-20) });
});

const PORT = process.env.PORT || 8080;
app.listen(PORT, () => console.log(`CHC Corporate API listening on port ${PORT}`));

// ── Telemetry sync store (Script 23 patch) ────────────────────
const syncStore = [];
const originalSyncPost = app._router?.stack?.find?.(r => r.route?.path === '/api/governance/sync');

// Replace /api/governance/sync with enhanced version
app.post('/api/governance/sync-enhanced', (req, res) => {
  const { source, executions, syncType, timestamp } = req.body;
  const sync = {
    source: source || 'UNKNOWN',
    executions: Array.isArray(executions) ? executions.length : 0,
    syncType: syncType || 'PUSH',
    timestamp: timestamp || new Date().toISOString(),
    receivedAt: new Date().toISOString(),
    syncId: 'sync-' + Date.now()
  };
  syncStore.push(sync);
  if (syncStore.length > 200) syncStore.shift();
  res.json({ success: true, message: 'Telemetry received', syncId: sync.syncId, total: syncStore.length });
});

app.get('/api/governance/syncs', (req, res) => {
  res.json({ success: true, count: syncStore.length, data: syncStore.slice(-20).reverse() });
});

// Final override to defeat security middleware resets
app.use((req, res, next) => {
  res.setHeader('Cross-Origin-Resource-Policy', 'cross-origin');
  res.setHeader('Cross-Origin-Opener-Policy', 'unsafe-none');
  res.setHeader('Access-Control-Allow-Origin', 'https://portal.coreholdingcorp.com');

app.use((req, res, next) => {
  res.removeHeader('Cross-Origin-Resource-Policy');
  res.removeHeader('Cross-Origin-Opener-Policy');
  res.setHeader('Cross-Origin-Resource-Policy', 'cross-origin');
  res.setHeader('Cross-Origin-Opener-Policy', 'unsafe-none');
  next();
});
